### ISSUE TITLE
Directly accept JS function rather than worker path

### ISSUE THREAD

**Issue by cstayyab** [un-ts/synckit#125] opened 2023-01-24 12:59 UTC
Is there any way or example to provide JS function to `runAsWorker` function instead of file path? Here is what I am trying to do:

```javascript
// this.__latest is an async function
    latest = () => {
        if (this._data) {
            // return this._latest[0];
            return createSyncFn(runAsWorker(this.__latest.bind(this)))();
        }
        return null;
    }
```

**Comment by JounQin** [comment] 2023-01-24 16:11
duplicate of https://github.com/un-ts/synckit/issues/119

**Closed** 2023-01-24 16:12 UTC
